spring:
  application:
    name: community

  datasource:
    url: jdbc:mysql://mysql:3306/community?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: My$tr0ngP@ssw0rd!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
