name: Run Tests on Push to Main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: My$tr0ngP@ssw0rd!
          MYSQL_DATABASE: community
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          sleep 20

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew
        working-directory: ./community

      - name: Run Tests with Spring test profile
        run: ./gradlew test -Dspring.profiles.active=test
        working-directory: ./community
